# Generated by Django 3.2 on 2021-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_urls', models.URLField()),
                ('followers', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('spotify_id', models.IntegerField()),
                ('images', models.JSONField()),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
    ]
