# Generated by Django 3.2 on 2021-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='external_urls',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='href',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='images',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
