# Generated by Django 3.2 on 2021-04-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20210413_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers_href',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='href',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='images',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
