# Generated by Django 3.2 on 2021-04-14 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_auto_20210414_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
